### PR TITLE
More config options! And some fixes because why not

### LINKED ISSUE #5: [Suggestion] Spider-placed Cobwebs should vanish after some time
Just to avoid having places eventually be covered in Cobwebs after numerous Spider attacks.

### LINKED ISSUE #7: Wither Boss doesn't start with full health when created
Now, I don't know exactly if it is a mod incompatibility, and this was before I got the sihywtcamd (I have it on now). But when I summon a wither (not with commands) he doesn't have full 600 heatlth rather he starts with 420/600 (spawns in with 200/600 but only heals up to that amount), anyways with him being summoned with commands he would have the 400 max health from sihywtcamd but that's not the issue.

The thing is I think him being summoned doesn't give his starting health enough time to get full like in vanilla where he starts with 200 (I think?) and heals up to 300 health, so I belive buffing his initial healing (or if you wish, make his entire regeneration buffed) would make him reach his maximum health.

I have recorded a video showing how much health the Wither starts with and I have attached a log as well to show the mod list.

[latest.log](https://github.com/stormdirus2/nox/files/7872434/latest.log)

And here is my video showing the wither being created with your mod and sihywtcamd: https://youtu.be/Vgy-O1fpuRg

### LINKED ISSUE #8: 1.18 - Request More Config Options
I would like to say that this mod is AWESOME. I'm so happy to have found it and is quickly becoming a MUST-HAVE for my fabric pack.

While I'm playing with it, however, I find there are some items I would like to tweak. I am not sure how difficult it would be to add a boolean option for items in your ReadME (per entity) and ship as a config, but if it's possible, I think it would be great! 

Thank you again for an awesome mod!

### LINKED ISSUE #9: 1.18 - Incompatibility with BetterEnd's Endslime
Hello,

I am experiencing a crash when exploring the End with the BetterEnd mod installed with Nox - A Mob and Difficulty Overhaul. It seems to occur when the chunk attempts to spawn an End Slime. I have made a fresh pack with just Nox and BetterEnd to confirm the incompatibility. Similarly, I am unable to use Endslime spawn eggs (although instead of crashing, it just doesn't spawn anything)

Minecraft Version: 1.18.1
Fabric API: 0.12.12
nox-1.0.0.jar
better-end-1.0.0.jar
crash log: https://pastebin.com/v9Vy8WGV

Posting on both mod issues just in case :D. Thank you!

### PR DESCRIPTION
**Pull request by AeiouEnigma**
Planning to keep this as a draft PR while I continue to go through Nox's features to implement a robust suite of options for the user.

Also implements some issue fixes.

Closes #5 
Closes #7 
Closes #8 
Closes #9

### CODE REVIEW

**Comment by AeiouEnigma** [comment]
For the most part, config options should now exist for anything that anyone might want to change. No options yet for Nox's broader suite of "enemies just do smarter things" changes, like strafing and whatnot.

**Comment by AeiouEnigma** [comment]
https://github.com/stormdirus2/nox/pull/6/commits/718ea45705b8bd20f9229eecae7834179bd10670 closes #9

**Comment by JoanLona** [comment]
Any help on how do i use these configs

**Comment by huerga1** [comment]
@AeiouEnigma any chance for 1.18.2? i really wanna use the mod with all the configs

**Comment by stormdirus2** [comment]
Oof. Yeah this is all mb.
I took so long coming back to this project, that when I did, I had to re-implement the config and stuff which inevitably caused conflict here.

Probably should've just merged before I tweaked literally everything.

**Comment by AeiouEnigma** [comment]
Working on updating this and fixing merge conflicts.

**Comment by AeiouEnigma** [comment]
Everything is probably in good order. Just need to make sure the default options are set appropriately and the en_us localization is finished for the new options.

**Comment by AeiouEnigma** [comment]
Closed by #25 (with much gratitude)

**Pull request closed without merging**
